general.import = [
  "./themes/themes/one_dark.toml"
]

[window]
opacity = 0.9
padding.x = 10
padding.y = 10
decorations = "none"

[font]
normal = { family ="Hack Nerd Font Mono", style = "Regular" }
bold = { family ="Hack Nerd Font Mono", style = "Bold" }
italic = { family ="Hack Nerd Font Mono", style = "Italic" }
bold_italic = { family ="Hack Nerd Font Mono", style = "Bold Italic" }
size = 14.0

[cursor]
style = "Beam"
unfocused_hollow = false

[env]
TERM = "xterm-256color"
